# Generated by Django 3.0.1 on 2019-12-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.TextField(verbose_name='publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalApp.Article')),
            ],
        ),
    ]
